%% Search for a specified operating point for the model - lumped_neck.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.11 and Simulink Control Design (TM) 6.0.
%
% Generated on: 21-Apr-2022 15:01:24

%% Specify the model name
model = 'lumped_neck';

pitch_operating_points = [0, 10, 35]; % degrees

%% Create the operating point specification object.
% Create the options
opt = findopOptions('DisplayReport','iter');

ls = cell(1,3);
op_points_pitch = cell(1,3);
for i = 1:length(pitch_operating_points)
   [ls{i}, op_points_pitch{i}] = linearize_pitch(model, pitch_operating_points(i), opt, 1);
end

%% Discretize models

ld = cell(1,3);

for i = 1:length(pitch_operating_points)
    ld{i} = c2d(ls{i}, 1e-3, 'tustin');
end

%% Polar plot of poles and zeros
pzmap(ld{:})
grid on
